# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(514, 407)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 40, 471, 341))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit.setReadOnly(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Справка"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Первоначально длина змейки составляет 2 блока, после того как змейка съедает яблоко, она становится на блок длиннее и так продолжается до того момента, как голова змейки коснется границ окна или своего хвоста. Каждое съеденное яблоко приносит одно очко, но есть и специальные яблоки, которые нужно успеть съесть за определенное время, и эти яблоки дают три очка. После ‘смерти’, данные игрока(его имя и результат) записываются в таблицу лидеров, которую можно найти в диалоговом окне. Игру можно поставить на паузу, путем нажатия английской кнопки \"P\" Для выхода из игры надо нажать клавишу \"esc\" Управление змейкой происходит посредством нажатия клавиш \"wasd\" либо \"←↑→↓\""))
        self.label.setText(_translate("Dialog", "Справка"))
